trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDirectory: 'TFKT/Day1'

steps:

- bash: |
    TERRAFORM_VERSION="1.13.3"
    wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Install Terraform'

- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'terraform-azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd $(terraformWorkingDirectory)
      terraform init

- task: AzureCLI@2
  displayName: 'Terraform Validate'
  inputs:
    azureSubscription: 'terraform-azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd $(terraformWorkingDirectory)
      terraform validate

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'terraform-azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd $(terraformWorkingDirectory)
      terraform plan